# Generated by Django 5.2.8 on 2025-11-29 10:10

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("title", models.CharField(max_length=500)),
                ("content", models.TextField()),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "documents",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["created_at"], name="documents_created_3c6eaa_idx"),
                    models.Index(fields=["title"], name="documents_title_3f6c9c_idx"),
                ],
            },
        ),
    ]
