# Generated by Django 5.2.8 on 2025-11-29 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ChatHistory",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("user", models.CharField(blank=True, max_length=255, null=True)),
                ("messages", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Chat histories",
                "db_table": "chat_history",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ToolLog",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("tool_name", models.CharField(max_length=100)),
                ("input_data", models.JSONField()),
                ("output_data", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "tool_logs",
                "ordering": ["-created_at"],
            },
        ),
    ]
